<?php

// =============================================================================
// Migration: create_users_table
// Generated by Laravel Breeze — creates the three auth-related tables in one
// migration so the framework ships as a cohesive unit.
// Tables: users, password_reset_tokens, sessions
// =============================================================================

use Illuminate\Database\Migrations\Migration; // Base class for all migrations
use Illuminate\Database\Schema\Blueprint;      // Fluent schema builder passed into closures
use Illuminate\Support\Facades\Schema;         // Entry-point for DDL (create, table, drop)

// Anonymous class syntax (Laravel 9+) — avoids class-name collisions between migrations.
return new class extends Migration
{
    /**
     * Run the migration: create tables.
     */
    public function up(): void
    {
        // ── users ─────────────────────────────────────────────────────────────
        // Core authentication identity. Separate from the `attendees` table which
        // holds contact/profile data. A User represents a login credential;
        // an Attendee represents a person registering for events.
        Schema::create('users', function (Blueprint $table) {
            $table->id();                                  // Auto-increment BIGINT primary key (uq)
            $table->string('name');                        // Display name shown in UI
            $table->string('email')->unique();             // Login identifier — unique constraint enforced at DB level
            $table->timestamp('email_verified_at')->nullable(); // NULL = unverified; set by email verification flow
            $table->string('password');                    // bcrypt hash — NEVER store plaintext
            $table->boolean('is_admin')->default(false);   // Role flag; true = access to admin routes/middleware
            $table->rememberToken();                       // 100-char nullable token for "remember me" sessions
            $table->timestamps();                          // created_at + updated_at (auto-managed by Eloquent)
        });

        // ── password_reset_tokens ─────────────────────────────────────────────
        // Stores short-lived tokens emailed to users who request a Breeze
        // password reset. The application also adds a custom security-question
        // recovery path that bypasses this table entirely.
        Schema::create('password_reset_tokens', function (Blueprint $table) {
            $table->string('email')->primary(); // One active token per email address
            $table->string('token');            // Hashed token (compared via Hash::check)
            $table->timestamp('created_at')->nullable(); // Used to expire old tokens
        });

        // ── sessions ──────────────────────────────────────────────────────────
        // Database-backed session driver (configured in config/session.php).
        // Allows server-side session invalidation (e.g., on password change).
        // ip_address length 45 supports IPv6 addresses (max 39 chars + safety margin).
        Schema::create('sessions', function (Blueprint $table) {
            $table->string('id')->primary();              // Session ID (random, stored in browser cookie)
            $table->foreignId('user_id')->nullable()->index(); // NULL for guest sessions; indexed for user-session lookup
            $table->string('ip_address', 45)->nullable(); // IPv4 or IPv6 client IP
            $table->text('user_agent')->nullable();       // Browser/client identifier
            $table->longText('payload');                  // Serialised (encrypted) session data
            $table->integer('last_activity')->index();    // Unix timestamp; indexed for garbage collection cleanup
        });
    }

    /**
     * Reverse the migration: drop tables in reverse creation order to respect
     * any foreign-key dependencies that may have been added later.
     */
    public function down(): void
    {
        Schema::dropIfExists('users');                  // dropIfExists is idempotent — safe to re-run
        Schema::dropIfExists('password_reset_tokens');
        Schema::dropIfExists('sessions');
    }
};
